// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLjmWdTM1Bmt8M-TCZWIfFbnvfr-sYuJ8',
    appId: '1:358167198248:web:6051a5e8e3007fd906131d',
    messagingSenderId: '358167198248',
    projectId: 'project2-b0c48',
    authDomain: 'project2-b0c48.firebaseapp.com',
    storageBucket: 'project2-b0c48.appspot.com',
    measurementId: 'G-PMPPWMZF22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYt4dwq27eoOs9u7UDLU7hvytlVuZd-7M',
    appId: '1:358167198248:android:5947f893e77e298006131d',
    messagingSenderId: '358167198248',
    projectId: 'project2-b0c48',
    storageBucket: 'project2-b0c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpYP2XN25E7VXDGw18aakSkOkZs7roM0',
    appId: '1:358167198248:ios:29d35438f3eefb7706131d',
    messagingSenderId: '358167198248',
    projectId: 'project2-b0c48',
    storageBucket: 'project2-b0c48.appspot.com',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpYP2XN25E7VXDGw18aakSkOkZs7roM0',
    appId: '1:358167198248:ios:29d35438f3eefb7706131d',
    messagingSenderId: '358167198248',
    projectId: 'project2-b0c48',
    storageBucket: 'project2-b0c48.appspot.com',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLjmWdTM1Bmt8M-TCZWIfFbnvfr-sYuJ8',
    appId: '1:358167198248:web:0540e05df58adf2b06131d',
    messagingSenderId: '358167198248',
    projectId: 'project2-b0c48',
    authDomain: 'project2-b0c48.firebaseapp.com',
    storageBucket: 'project2-b0c48.appspot.com',
    measurementId: 'G-FLXW6SHYG0',
  );
}
